### ISSUE TITLE
FloydWarshall demo

### ISSUE THREAD

**Issue by yhlim1225** [yhlim1225/OSS_G6#6]
컴파일하면 

> demo_source/floydwarshall_demo.cpp:33:239:` error: narrowing conversion of ‘1.0e+9’ from ‘double’ to ‘int’ inside { } [-Wnarrowing]

라고 나오는데 INF 값이 너무 커서 문제있는것 같습니다.

**Comment by nighthalllo** [comment]
Bug fix completed
